In [1]:
from sklearn.ensemble import RandomForestRegressor
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import mean_squared_error
from xgboost import XGBRegressor as xgbr#from sklearn.gaussian_process import GaussianProcessRegressor
#from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C
#from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
#from sklearn.pipeline import Pipeline, FeatureUnion

In [2]:
data = pd.read_csv('ff_x.csv')
target = np.load("ff_y.npy",allow_pickle=True)
#total = pd.concat([data,target],axis=1)
data = data.drop(["Unnamed: 0"],1)
#data = np.array(data)
'''all_ = pd.DataFrame(data=data)
all_['target'] = target
all_ = all_.sample(frac=1)
X = all_.drop(["target"],1)
y = all_['target']'''
data.replace([np.inf, -np.inf], np.nan, inplace=True) 
data = data.fillna(0)
scaler = StandardScaler()
scaler.fit(data)
data =scaler.transform(data)


In [3]:
#total = total.drop(['Unnamed: 0','Unnamed: 0.1','Unnamed: 0'],1)
#X = total.drop(['Ki (nM)'],1)
#y = total['Ki (nM)']
target =target.astype(np.float)
data

array([[ 0.88254416,  1.287247  ,  3.60530755, ..., -0.35274258,
         2.68720008, -4.33665859],
       [ 0.1311666 ,  0.33516731, -0.16768872, ..., -0.59887586,
         1.67430362,  1.27263393],
       [ 0.1311666 ,  0.33516731, -0.16768872, ..., -0.59887586,
         1.67430362,  1.27263393],
       ...,
       [-0.35868485, -0.6307977 , -0.16768872, ...,  0.75001202,
        -0.31027937, -0.24092796],
       [-0.26328343, -0.53645099, -0.16768872, ...,  0.75001202,
        -0.31027937, -0.24092796],
       [-0.35868485, -0.6307977 , -0.16768872, ...,  0.75001202,
        -0.31027937, -0.24092796]])

In [4]:
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.10, random_state=42)

In [5]:
regr = RandomForestRegressor(max_depth=30,n_estimators=1000)
regr.fit(X_train, y_train)
regr.score(X_train,y_train)

xgb = xgbr(max_depth=20,n_estimators=1000)
xgb.fit(X_train,y_train)

#xgr.score(X_train,y_train)
'''kernel=C(1.0, (1e-3, 1e3)) * RBF(10, (1e-2, 1e2))
gp = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=9)
gp.fit(X_train,y_train)'''
vr = SVR()
vr.fit(X_train ,y_train)
vr.score(X_train,y_train)
regr.score(X_train,y_train)


NameError: name 'SVR' is not defined

In [84]:
#predictions_rf = regr.predict(X_test)
predictions_xg = xgbr.predict(X_test)
predictions =(predictions_rf+predictions_xg)/2
comp =(predictions_ ,y_test)
numerics = ['int16','int32','int64','float16','float32','float64']
y_test = y_test.astype(np.float) 

In [31]:
xgb.score(X_train,y_train)
predicts = xgb.predict(X_test)
corr = np.corrcoef(predicts,y_test)


array([[1.        , 0.88550256],
       [0.88550256, 1.        ]])

In [27]:
d = {'actual': y_test, 'predicted': predictions}
eval = pd.DataFrame(data=d , columns = ['actual', 'predicted'])
eval.to_csv("ensemble.csv")

NameError: name 'predictions' is not defined

In [66]:
gp.score(X_train,y_train)
y_pred,sigma = gp.predict(X_test, return_std=True)
y_pred = y_pred+sigma
corr =np.corrcoef(y_pred,y_test)
gaussian = pd.DataFrame()
gaussian['pred'] = y_pred
gaussian['actual'] = y_test
gaussian.to_csv("gaussian_res.csv")

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\gaussian_process\gpr.py:346: UserWarning: Predicted variances smaller than 0. Setting those variances to 0.
  warnings.warn("Predicted variances smaller than 0. "


In [71]:
pred_svr = svr.predict(X_test)
np.corrcoef(pred_svr , y_test)

array([[1.        , 0.34510285],
       [0.34510285, 1.        ]])

In [77]:
y_test[64]

3800.0

In [34]:
cv_results = xgb.cv(
    params,
    dtrain,
    num_boost_round=num_boost_round,
    seed=42,
    nfold=5,
    metrics={'mae'},
    early_stopping_rounds=10
)
cv_results

NameError: name 'params' is not defined

In [14]:
ff =pd.read_csv("ff.csv")
X = ff.drop(['Unnamed: 0','ID','Ki (nM)','IC50 (nM)' ,'Kd (nM)' ,'EC50 (nM)' ,'ligand_name'],1)
y = ff['Ki (nM)']

In [18]:
numerics = ['int16','int32','int64','float16','float32','float64']
numerical_vars = list(X.select_dtypes(include=numerics).columns)
X= X[numerical_vars]
X.replace([np.inf, -np.inf ,], np.nan, inplace=True) 
#X =X.dropna()
X.fillna(0)
X.shape

(360, 426)

In [23]:
ind =[]
for g in y.index:
     if y[g].startswith(">")==True:
        ind.append(y[g])
type(ind)
for i in ind:
    y =y.replace(i,int(i.split(">")[1]))

In [30]:
X.to_csv("ff_x.csv")
y.to_csv("ff_y.csv")
np.save('ff_y.npy', y) # save
 # load

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  


In [98]:
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor(n_neighbors=7,weights='distance')
neigh.fit(X_train, y_train)
neigh.score(X_train, y_train)
pred_knn =neigh.predict(X_test)
np.corrcoef(pred_knn,y_test)


array([[1.        , 0.87307902],
       [0.87307902, 1.        ]])

In [4]:
import pandas as pd
import numpy as np
f = pd.read_csv("actual_and_predicted.csv")
act = f['actual']
pred = f['predicted']
np.corrcoef(act,pred)

array([[1.        , 0.95742313],
       [0.95742313, 1.        ]])

In [99]:
from sklearn.linear_model import LinearRegression, Ridge

In [104]:
ridge = Ridge(max_iter=10)
ridge.fit(X_train,y_train)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=10, normalize=False,
      random_state=None, solver='auto', tol=0.001)

In [105]:
ridge.score(X_train,y_train)

0.32703756967623887

In [107]:
X_train

array([[-0.13394739, -0.11915472, -0.16768872, ..., -1.61829399,
        -0.76141955,  0.45598956],
       [-0.45408626, -0.69305448, -0.16768872, ...,  0.75001202,
        -0.31027937, -0.24092796],
       [ 0.67057565,  1.05518591, -0.16768872, ..., -0.59887586,
         1.67430362,  1.27263393],
       ...,
       [-0.84114803, -1.01765363, -0.16768872, ...,  0.75001202,
        -0.31027937, -0.24092796],
       [-0.34938229, -0.48550463, -0.16768872, ...,  0.75001202,
        -0.31027937, -0.24092796],
       [ 0.51661538,  0.70663756, -0.16768872, ..., -0.59887586,
         1.67430362,  1.27263393]])

In [4]:
!pip install xgboost


Error processing line 1 of C:\Users\Administrator\Anaconda3\envs\my-rdkit-env\lib\site-packages\matplotlib-3.2.1-py3.7-nspkg.pth:

  Traceback (most recent call last):
    File "C:\Users\Administrator\Anaconda3\envs\my-rdkit-env\lib\site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 580, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored


In [32]:
import pickle
file_name = "xgb_reg.pkl"

# save
pickle.dump(xgb, open(file_name, "wb"))

# load
'''xgb_model_loaded = pickle.load(open(file_name, "rb"))

# test
ind = 1
test = X_val[ind]
xgb_model_loaded.predict(test)[0] == xgb_model.predict(test)[0]'''

'xgb_model_loaded = pickle.load(open(file_name, "rb"))\n\n# test\nind = 1\ntest = X_val[ind]\nxgb_model_loaded.predict(test)[0] == xgb_model.predict(test)[0]'

In [33]:
data = pd.read_csv('ff_x.csv')

In [37]:
data =data.drop(["Unnamed: 0"],1)

In [39]:
features = [d for d in data.columns]

In [42]:
features = pd.DataFrame(data=features)
features.to_csv("features_426.csv")

In [ ]:
faet